### PR TITLE
fix: create-hakit missing deploy script + App.tsx ThemeProvider being outside HassConnect provider

### LINKED ISSUE #85: Setup CLI issues
**Describe the bug**
1. `useHass must be used within a HassProvider, have you wrapped your application in <HassConnect hassUrl={HASS_URL} />?`
2. There is no deploy script in package.json

**To Reproduce**
Steps to reproduce the behaviour of bug number 1:
1. `npm create hakit@latest`
1. Ensure your token and home-assistant URLs are valid in the `.env` file
1. `npm i`
1. `npm run dev`
1. Notice the first error mentioned

Steps to reproduce the behaviour of bug number 1:
1. `npm create hakit@latest`
1. `npm i`
1. `npm run publish`
1. Notice the first error `Missing script: "deploy"`

**Expected behavior**
After running the creation CLI, I should have a working project ready to go :)

**System Info (please complete the following information):**
 - IDE: Webstorm
 - Browser: chrome
 - npm version: 9
 - node version: 18

### PR DESCRIPTION
**Pull request by yann510**
closes #85

### CODE REVIEW

**Comment by shannonhochkins** [comment]
Thanks legend!

Just curious, did the deploy script work for you? 

I'm working on an addon to serve custom pages from the sidebar so there's an easy access point too

**Review by shannonhochkins — APPROVED** [review]
Nice work, very much appreciated! - i'll do some final cleanup and add more documentation then release

**Comment by yann510** [comment]
> Just curious, did the deploy script work for you?

Yes, it did deploy properly, but I had to use an `iframe_panel` as I wanted it in the sidebar.
It's not so great though as right now I need to restart for every deployment, but since the dev experience is really great with vite, I guess that's not much of a problem.

> I'm working on an addon to serve custom pages from the sidebar so there's an easy access point too

Yeah, that would be awesome!!


> Nice work, very much appreciated! - i'll do some final cleanup and add more documentation then release

Thanks, man I've made some great progress with my dashboard, here's a first sneak peak.
Btw what you have built is really easy to work with and the sync-type script is a life saver!!!


image

I'll be implementing a TV card component at some point as I have that in my current setup, but I want it in react :)
Would you be interested to have it in your project?

**Comment by shannonhochkins** [comment]
Nice work man! Looking good! And I'll be happy to introduce something I think others would use, you might have to explain it a little more to me though, what exactly would a tv card do? Just play a stream of a channel as a card?

**Comment by yann510** [comment]
Currently I'm using this one, but I want full control of it in react: https://github.com/usernein/tv-card

Also one thing I've been adding is loading states, like disabling the card when it's changing state so you can't double toggle a light for example. Once I have something good enough I'll push it on my repo and show you what it looks like :)

**Comment by shannonhochkins** [comment]
I really appreciate that you're literally taking on jobs I've thought of but not started yet! Thanks man!

**Comment by shannonhochkins** [comment]
Regarding the tv remote card, I understand now! I like it, and can I suggest some ideas? Whilst building these cards and components, I've often thought about what would be the best way I could build this, to make me want to use the app over the actual remote haha, maybe a button / toggle card, that when pressed takes up the whole screen on mobile, and a large portion on desktop, to provide the best possible  ui to make it easier to use than a real remote 😀

**Comment by yann510** [comment]
That's a great idea, once I have my full dashboard ready, I'll start working on this :)

**Comment by shannonhochkins** [comment]
This might also be a good addition as a popup for the media player!

**Pull request merged**
