### PR TITLE
feat: allow breakpoint queries on PersonCard

### PR DESCRIPTION
**Pull request by jenseo**
Since we decided to go with a compositional approach where we allow PersonCard's as children to the FamilyCard, it makes sense to allow the user to easily change the width of the individual cards on different screen sizes

### CODE REVIEW

**Comment by jenseo** [comment]
Ah, I see! I have two entities and wanted two columns on smallest screen, but I believe it's one col there by default. But sounds great to disable it by default but give the user the option to override it 😊

**Comment by shannonhochkins** [comment]
> Ah, I see! I have two entities and wanted two columns on smallest screen, but I believe it's one col there by default. But sounds great to disable it by default but give the user the option to override it 😊

I'll merge your changes and update it so it's using a default only provided when used within a FamilyCard, that way by default it'll be column based if used outside of the FamilyCard

```
const childrenWithKeys = Children.map(children, (child, index) => {
  if (isValidElement<PersonCardProps>(child)) {
    return cloneElement(child, {
      key: child.key || index,
      className: `entity-count-${count}`,
      disableColumns: child.disableColumns ?? true,
    });
  }
  return child;
});
```

**Comment by jenseo** [comment]
You're the man! 🚀

**Comment by shannonhochkins** [comment]
```
const childrenWithKeys = Children.map(children, (child, index) => {
  if (isValidElement<PersonCardProps>(child)) {
    // if they've defined columns, we don't want to override it
    const columns: BreakPoint[] = ['xxs', 'xs', 'sm', 'md', 'lg', 'xlg'];
    const hasColumnDefinition = columns.some((key) => typeof child.props[key] === 'number');
    const disableColumns = hasColumnDefinition ? false : child.props.disableColumns ?? true;
    return cloneElement(child, {
      key: child.key || index,
      className: disableColumns ? `entity-count-${count}` : '',
      disableColumns,
    });
  }
  return child;
});
```

This way, users can simply just add in the column breakpoint prop, without having to provide the disableColumns prop as well :)

**Pull request merged**
